#!/bin/bash

# Create and use a new builder instance
docker buildx create --name multiarch --use

# Build the multi-platform image using the pre-built application
docker buildx build . -t $IMAGE_NAME --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x --push
